package com.noteops.agent.service.trend;

import com.noteops.agent.model.trend.TrendActionType;
import com.noteops.agent.model.trend.TrendAnalysisPayload;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

@Component
public class StubTrendAgent implements TrendAgent {

    @Override
    public TrendAnalysisPayload analyze(AnalyzeTrendRequest request) {
        String focus = collapse(request.title());
        List<String> topicTags = inferTopicTags(request);
        boolean noteWorthy = request.normalizedScore() >= 60.0d;
        boolean ideaWorthy = request.normalizedScore() >= 85.0d || containsAny(focus, "launch", "workflow", "platform");
        TrendActionType suggestedAction = ideaWorthy
            ? TrendActionType.PROMOTE_TO_IDEA
            : noteWorthy
                ? TrendActionType.SAVE_AS_NOTE
                : TrendActionType.IGNORE;
        String summary = summarize(focus, request.sourceType().name());
        String whyItMatters = whyItMatters(focus, request.sourceType().name(), request.normalizedScore());

        return new TrendAnalysisPayload(
            summary,
            whyItMatters,
            topicTags,
            signalType(request),
            noteWorthy,
            ideaWorthy,
            suggestedAction,
            "This analysis is generated by the local stub TrendAgent using source type, title, score, and basic keyword heuristics."
        );
    }

    private List<String> inferTopicTags(AnalyzeTrendRequest request) {
        Set<String> tags = new LinkedHashSet<>();
        String value = collapse(request.title()).toLowerCase(Locale.ROOT);
        if (containsAny(value, "agent", "agents")) {
            tags.add("agents");
        }
        if (containsAny(value, "memory", "retrieval", "rag")) {
            tags.add("memory");
        }
        if (containsAny(value, "tool", "tooling", "sdk")) {
            tags.add("tooling");
        }
        if (containsAny(value, "code", "coding", "repo")) {
            tags.add("coding");
        }
        if (request.sourceType().name().equals("GITHUB")) {
            tags.add("repository");
        }
        if (tags.isEmpty()) {
            tags.add("trend");
        }
        return new ArrayList<>(tags);
    }

    private String summarize(String title, String sourceType) {
        return switch (sourceType) {
            case "HN" -> "HN discussion signal: " + title;
            case "GITHUB" -> "GitHub project signal: " + title;
            default -> "Trend signal: " + title;
        };
    }

    private String whyItMatters(String title, String sourceType, double normalizedScore) {
        return String.format(
            Locale.ROOT,
            "%s surfaced a %.2f score around %s, which makes it a strong candidate for the controlled Trend inbox.",
            sourceType,
            normalizedScore,
            title
        );
    }

    private String signalType(AnalyzeTrendRequest request) {
        return request.sourceType().name().equals("GITHUB") ? "PROJECT" : "DISCUSSION";
    }

    private boolean containsAny(String value, String... keywords) {
        for (String keyword : keywords) {
            if (value.contains(keyword)) {
                return true;
            }
        }
        return false;
    }

    private String collapse(String value) {
        String normalized = value == null ? "" : value.trim().replaceAll("\\s+", " ");
        return normalized.length() > 140 ? normalized.substring(0, 140).trim() : normalized;
    }
}
